# Generated by Django 3.0.6 on 2020-06-03 11:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biling_and_payment', '0002_auto_20200603_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compteuser',
            name='date_expiration',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 4, 11, 39, 23, 37314)),
        ),
    ]
