# Generated by Django 3.0.6 on 2020-06-03 11:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biling_and_payment', '0003_auto_20200603_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='compteuser',
            name='nom_forfait',
            field=models.CharField(default='aucun forfait', max_length=25, unique=True),
        ),
        migrations.AddField(
            model_name='compteuser',
            name='userId',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AddField(
            model_name='forfait',
            name='expire_days',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='compteuser',
            name='date_expiration',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 4, 11, 54, 11, 692258)),
        ),
    ]
