# Generated by Django 3.0.6 on 2020-06-03 13:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('biling_and_payment', '0004_auto_20200603_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='compteuser',
            name='date_activation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='compteuser',
            name='date_expiration',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
