# Generated by Django 3.0.6 on 2020-06-03 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biling_and_payment', '0005_auto_20200603_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compteuser',
            name='nom_forfait',
            field=models.CharField(default='aucun forfait', max_length=25),
        ),
    ]
