# Generated by Django 3.0.6 on 2020-06-04 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biling_and_payment', '0006_auto_20200603_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forfait',
            name='valeur',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
